### ISSUE TITLE
Bundler Errors with Hashie

### ISSUE THREAD

**Issue by camdub** [bobbrez/linkedin2#7]
I am getting a `Bundler could not find compatible versions for gem "hashie"` error. 

Grape is using version `3.0.0` of Hashe, and linkedin2 is using `2.1.1`.

Can we bump the Hashie version?

**Comment by joshjordan** [comment]
It looks like Hashie 3 does not break the Mash API, so this should be fine.
I don't want to bump it because there may be others stuck on ~> 2.1.1, but
I did loosen the restriction. If you refer to the github repo in your
gemfile, or convince @bobbrez to release the next gem version, you should
be good to go.
